modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MysticMods/Druidcraft/issues"

[[mods]]
modId="druidcraft"
version="0.4.2"
mcversion= "1.15,"
displayName="Druidcraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/druidcraft"
credits="Java, Forge, MCP, Minecraft, and the Mystic team for supporting me!"
authors="VulpTheHorseDog"
description='''
A druid-focused splice-of-life mod that's currently in very early stages.

Regardless, I hope you enjoy the features as they're rolled out! :)
'''

[[dependencies.druidcraft]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.9,)"
    ordering="NONE"
    side="BOTH"