modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MysticMods/Druidcraft/issues"

[[mods]]
modId="druidcraft"
version="0.3.1"
mcversion= "1.14,"
displayName="Druidcraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/druidcraft"
credits="Java, Forge, MCP, Minecraft, and the Mystic team for supporting me!"
authors="VulpTheHorseDog"
description='''
A druid-focused splice-of-life mod that's currently in very early stages.

Regardless, I hope you enjoy the features as they're rolled out! :)
'''

[[dependencies.druidcraft]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.70,)"
    ordering="NONE"
    side="BOTH"